# Generated by Django 5.0.4 on 2024-07-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='number_of_patients',
            field=models.IntegerField(default=0),
        ),
    ]
