# Generated by Django 5.0.4 on 2024-07-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_number_of_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='number_of_patients',
        ),
    ]
