# Generated by Django 5.0.4 on 2024-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_number_of_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default='01010100', max_length=15),
            preserve_default=False,
        ),
    ]
