# Generated by Django 5.0.4 on 2024-11-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
    ]
