# Generated by Django 5.0.4 on 2024-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_remove_appointment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescription/'),
        ),
    ]
