# Generated by Django 5.0.4 on 2024-11-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.ImageField(blank=True, null=True, upload_to='report/'),
        ),
    ]
