# Generated by Django 5.0.4 on 2024-07-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='doctor/images/')),
                ('description', models.TextField()),
                ('education', models.TextField()),
                ('pasaing_year', models.CharField(max_length=4)),
                ('experience', models.CharField(max_length=2)),
                ('fee', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dr_service_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(default='Closed', max_length=60)),
                ('monday', models.CharField(default='Closed', max_length=60)),
                ('tuesday', models.CharField(default='Closed', max_length=60)),
                ('wednesday', models.CharField(default='Closed', max_length=60)),
                ('thursday', models.CharField(default='Closed', max_length=60)),
                ('friday', models.CharField(default='Closed', max_length=60)),
                ('saturday', models.CharField(default='Closed', max_length=60)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialities'),
        ),
    ]
