# Generated by Django 5.0.4 on 2024-07-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_number_of_patients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='pasaing_year',
            new_name='passing_year',
        ),
    ]
