# Generated by Django 5.0.4 on 2024-07-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_number_of_patient_per_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number_of_patient_per_day',
        ),
    ]
